import type { Metadata } from "next";
import { Space_Grotesk, Lato } from "next/font/google";
import Script from "next/script";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "assets/images/favicon/icon.png",
  manifest: "/manifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="assets/css/all.min.css"
          precedence="default"
        />
        <link
          rel="stylesheet"
          href="assets/css/slick.css"
          precedence="default"
        />
        <link
          rel="stylesheet"
          href="assets/css/bootstrap.min.css"
          precedence="default"
        />
        <link
          rel="stylesheet"
          href="assets/css/style.css"
          precedence="default"
        />
        <link
          rel="stylesheet"
          href="assets/css/media-query.css"
          precedence="default"
        />
      </head>
      <body className={`${spaceGrotesk.variable} ${lato.variable}`}>
        {children}
      </body>
      <Script src="assets/js/bootstrap.bundle.min.js" />
      <Script src="assets/js/jquery-min-3.6.0.js" />
      <Script src="assets/js/slick.min.js" />
      {/* <Script src="assets/js/modal.js" /> */}
      <Script src="assets/js/custom.js" />
    </html>
  );
}
